name: CI

on:
  push:
    branches: [ main ]
  delete:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BINARY: "autoCompletion"

jobs:
  clean_repo:
    name: Delete useless files
    runs-on: ubuntu-latest
    env:
      USELESS_FILES_REGEX: (.*\.gc(no|da|ov))$|(.*\.(a|o))$|(.*~)$|^(#.*#)$|(.*(?i)pain_au_chocolat.*)|^tmp\/.*|.*\/tmp\/.*
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Find useless files recursively
        run: |
          USELESS_FILES=$(find . -type f -printf '%P\n' | { grep -P "${{ env.USELESS_FILES_REGEX }}" || true; })
          if [ "$USELESS_FILES" != "" ]; then
              IFS=$'\n'$'\r'
              for LINE in $USELESS_FILES; do
                  echo "::error file=${LINE},line=1,col=1,title=Useless file detected::${LINE}"
              done
              echo "FAIL_TASK=true" >> "$GITHUB_ENV"
          else
              echo "FAIL_TASK=false" >> "$GITHUB_ENV"
          fi
      - name: Check if task failed
        if: env.FAIL_TASK == 'true'
        run: exit 1

  check_build:
    name: Check if the program build correctly
    runs-on: ubuntu-latest
    needs: [clean_repo]
    container: epitechcontent/epitest-docker:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: make
        timeout-minutes: 5

      - run: make clean

      - name: Check executables
        run: |
          echo "FAIL_TASK=false" >> "$GITHUB_ENV"
          BINARIE="${{ env.BINARY }}"
          IFS=$','
          for BIN in $BINARY; do
            if [ ! -f "${BIN}" ]; then
              echo "::error file=${BIN},title=Binary not found::${BIN}"
              echo "FAIL_TASK=true" >> "$GITHUB_ENV"
            fi
            if [ ! -x "${BIN}" ]; then
              echo "::error file=${BIN},title=Binary is not executable::${BIN}"
              echo "FAIL_TASK=true" >> "$GITHUB_ENV"
            fi
          done
      - name: Check if task failed
        if: env.FAIL_TASK == 'true'
        run: exit

  run_test:
    name: Check if the program pass all unit test
    runs-on: ubuntu-latest
    needs: [check_build]
    container: epitechcontent/epitest-docker:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Unit Tests
        run: make tests_run
  
  mirror:
    name: Push content of the current repo on mirror
    runs-on: ubuntu-latest
    needs: [run_test]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2025/B-SYN-400-NAN-4-1-autoCompletion-matthis.lesur.git
          ssh_private_key:
            ${{ secrets.SSH_KEY }}
