name: CI

on:
  push:
    branches: [ main ]
  delete:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BINARY: "autoCompletion"

jobs:
  check_build:
    name: Check if the program build correctly
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: make
        timeout-minutes: 5

      - run: make clean

      - name: Check executables
        run: |
          echo "FAIL_TASK=false" >> "$GITHUB_ENV"
          BINARIE="${{ env.BINARY }}"
          IFS=$','
          for BIN in $BINARY; do
            if [ ! -f "${BIN}" ]; then
              echo "::error file=${BIN},title=Binary not found::${BIN}"
              echo "FAIL_TASK=true" >> "$GITHUB_ENV"
            fi
            if [ ! -x "${BIN}" ]; then
              echo "::error file=${BIN},title=Binary is not executable::${BIN}"
              echo "FAIL_TASK=true" >> "$GITHUB_ENV"
            fi
          done
      - name: Check if task failed
        if: env.FAIL_TASK == 'true'
        run: exit 1

  mirror:
    name: Push content of the current repo on mirror
    runs-on: ubuntu-latest
    needs: [check_build]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2025/B-SYN-400-NAN-4-1-autoCompletion-matthis.lesur.git
          ssh_private_key:
            ${{ secrets.SSH_KEY }}
